# Generated by Django 4.2 on 2023-05-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("youtube_scrape", "0002_channel_delete_input"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=50)),
                ("channel_title", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("tags", models.TextField()),
                ("published_at", models.DateTimeField()),
                ("thumbnail", models.URLField()),
                ("channel_id", models.CharField(max_length=50)),
                ("view_count", models.IntegerField()),
                ("like_count", models.IntegerField()),
                ("comment_count", models.IntegerField()),
                ("favorite_count", models.IntegerField()),
                ("duration", models.DurationField()),
                ("definition", models.CharField(max_length=50)),
                ("caption", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Channel",
        ),
    ]
