# Generated by Django 4.2 on 2023-05-02 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("youtube_scrape", "0003_video_delete_channel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Video",
            new_name="Youtube_Data",
        ),
    ]
