# Generated by Django 4.2 on 2023-05-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("youtube_scrape", "0004_rename_video_youtube_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="YourModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="youtube_data",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
