# Generated by Django 4.2 on 2023-05-03 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("youtube_scrape", "0005_yourmodel_alter_youtube_data_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YourModel",
        ),
    ]
