# Generated by Django 4.2 on 2023-05-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("youtube_scrape", "0006_delete_yourmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtube_data",
            name="caption",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="youtube_data",
            name="channel_id",
            field=models.CharField(max_length=5255),
        ),
        migrations.AlterField(
            model_name="youtube_data",
            name="definition",
            field=models.CharField(max_length=255),
        ),
    ]
