# Generated by Django 4.2 on 2023-05-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("youtube_scrape", "0008_alter_youtube_data_caption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtube_data",
            name="duration",
            field=models.TextField(),
        ),
    ]
