# Generated by Django 4.2 on 2023-05-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("youtube_scrape", "0009_alter_youtube_data_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtube_data",
            name="caption",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="youtube_data",
            name="channel_id",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="youtube_data",
            name="channel_title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="youtube_data",
            name="comment_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="youtube_data",
            name="definition",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="youtube_data",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="youtube_data",
            name="duration",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="youtube_data",
            name="favorite_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="youtube_data",
            name="like_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="youtube_data",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="youtube_data",
            name="tags",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="youtube_data",
            name="thumbnail",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="youtube_data",
            name="video_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="youtube_data",
            name="view_count",
            field=models.IntegerField(null=True),
        ),
    ]
